"dead-letter-queue": "yes"
"filebeat": "yes"
"logs-auditd_manager.auditd-acc": "yes"
"logs-auditd_manager.auditd-default": "yes"
"logs-auditd_manager.auditd-ont": "yes"
"logs-auditd_manager.auditd-prd": "yes"
"logs-auditd_manager.auditd-tst": "yes"
"logs-auditd.log-acc": "yes"
"logs-auditd.log-default": "yes"
"logs-auditd.log-ont": "yes"
"logs-auditd.log-prd": "yes"
"logs-auditd.log-tst": "yes"
"logs-beats-raw": "yes"
"logs-checkpoint.firewall-acc": "yes"
"logs-checkpoint.firewall-default": "yes"
"logs-checkpoint.firewall-ont": "yes"
"logs-checkpoint.firewall-prd": "yes"
"logs-checkpoint.firewall-tst": "yes"
"logs-cyberarkpas.audit-acc": "yes"
"logs-cyberarkpas.audit-default": "yes"
"logs-cyberarkpas.audit-ont": "yes"
"logs-cyberarkpas.audit-prd": "yes"
"logs-cyberarkpas.audit-tst": "yes"
"logs-database": "yes"
"logs-docker.container_logs-acc": "yes"
"logs-docker.container_logs-default": "yes"
"logs-docker.container_logs-ont": "yes"
"logs-docker.container_logs-prd": "yes"
"logs-docker.container_logs-tst": "yes"
"logs-elastic_agent-acc": "yes"
"logs-elastic_agent-default": "yes"
"logs-elastic_agent-fleetserver": "yes"
"logs-elastic_agent-ont": "yes"
"logs-elastic_agent-prd": "yes"
"logs-elastic_agent-tst": "yes"
"logs-elastic_agent.auditbeat-acc": "yes"
"logs-elastic_agent.auditbeat-default": "yes"
"logs-elastic_agent.auditbeat-ont": "yes"
"logs-elastic_agent.auditbeat-prd": "yes"
"logs-elastic_agent.auditbeat-tst": "yes"
"logs-elastic_agent.endpoint_security-acc": "yes"
"logs-elastic_agent.endpoint_security-default": "yes"
"logs-elastic_agent.endpoint_security-ont": "yes"
"logs-elastic_agent.endpoint_security-prd": "yes"
"logs-elastic_agent.endpoint_security-tst": "yes"
"logs-elastic_agent.filebeat-acc": "yes"
"logs-elastic_agent.filebeat-default": "yes"
"logs-elastic_agent.filebeat-ont": "yes"
"logs-elastic_agent.filebeat-prd": "yes"
"logs-elastic_agent.filebeat-tst": "yes"
"logs-elastic_agent.fleet_server-acc": "yes"
"logs-elastic_agent.fleet_server-default": "yes"
"logs-elastic_agent.fleet_server-fleetserver": "yes"
"logs-elastic_agent.fleet_server-ont": "yes"
"logs-elastic_agent.fleet_server-prd": "yes"
"logs-elastic_agent.fleet_server-tst": "yes"
"logs-elastic_agent.heartbeat-acc": "yes"
"logs-elastic_agent.heartbeat-default": "yes"
"logs-elastic_agent.heartbeat-ont": "yes"
"logs-elastic_agent.heartbeat-prd": "yes"
"logs-elastic_agent.heartbeat-tst": "yes"
"logs-elastic_agent.metricbeat-acc": "yes"
"logs-elastic_agent.metricbeat-default": "yes"
"logs-elastic_agent.metricbeat-fleetserver": "yes"
"logs-elastic_agent.metricbeat-ont": "yes"
"logs-elastic_agent.metricbeat-prd": "yes"
"logs-elastic_agent.metricbeat-tst": "yes"
"logs-elastic_agent.osquerybeat-acc": "yes"
"logs-elastic_agent.osquerybeat-default": "yes"
"logs-elastic_agent.osquerybeat-ont": "yes"
"logs-elastic_agent.osquerybeat-prd": "yes"
"logs-elastic_agent.osquerybeat-tst": "yes"
"logs-elastic_agent.status_change-acc": "yes"
"logs-elastic_agent.status_change-default": "yes"
"logs-elastic_agent.status_change-ont": "yes"
"logs-elastic_agent.status_change-prd": "yes"
"logs-elastic_agent.status_change-tst": "yes"
"logs-elasticsearch.deprecation-default": "yes"
"logs-elasticsearch.server-default": "yes"
"logs-endpoint.alerts-acc": "yes"
"logs-endpoint.alerts-default": "yes"
"logs-endpoint.alerts-ont": "yes"
"logs-endpoint.alerts-prd": "yes"
"logs-endpoint.alerts-tst": "yes"
"logs-endpoint.events.api-acc": "yes"
"logs-endpoint.events.api-default": "yes"
"logs-endpoint.events.api-ont": "yes"
"logs-endpoint.events.api-prd": "yes"
"logs-endpoint.events.api-tst": "yes"
"logs-endpoint.events.file-acc": "yes"
"logs-endpoint.events.file-dafault": "yes"
"logs-endpoint.events.file-default": "yes"
"logs-endpoint.events.file-ont": "yes"
"logs-endpoint.events.file-prd": "yes"
"logs-endpoint.events.file-tst": "yes"
"logs-endpoint.events.library-acc": "yes"
"logs-endpoint.events.library-default": "yes"
"logs-endpoint.events.library-ont": "yes"
"logs-endpoint.events.library-prd": "yes"
"logs-endpoint.events.library-tst": "yes"
"logs-endpoint.events.network-acc": "yes"
"logs-endpoint.events.network-default": "yes"
"logs-endpoint.events.network-ont": "yes"
"logs-endpoint.events.network-prd": "yes"
"logs-endpoint.events.network-tst": "yes"
"logs-endpoint.events.process-acc": "yes"
"logs-endpoint.events.process-default": "yes"
"logs-endpoint.events.process-ont": "yes"
"logs-endpoint.events.process-prd": "yes"
"logs-endpoint.events.process-tst": "yes"
"logs-endpoint.events.registry-acc": "yes"
"logs-endpoint.events.registry-default": "yes"
"logs-endpoint.events.registry-ont": "yes"
"logs-endpoint.events.registry-prd": "yes"
"logs-endpoint.events.registry-tst": "yes"
"logs-endpoint.events.security-acc": "yes"
"logs-endpoint.events.security-default": "yes"
"logs-endpoint.events.security-ont": "yes"
"logs-endpoint.events.security-prd": "yes"
"logs-endpoint.events.security-tst": "yes"
"logs-entityanalytics_ad.device-acc": "yes"
"logs-entityanalytics_ad.device-default": "yes"
"logs-entityanalytics_ad.device-ont": "yes"
"logs-entityanalytics_ad.device-prd": "yes"
"logs-entityanalytics_ad.device-tst": "yes"
"logs-entityanalytics_ad.entity-acc": "yes"
"logs-entityanalytics_ad.entity-default": "yes"
"logs-entityanalytics_ad.entity-ont": "yes"
"logs-entityanalytics_ad.entity-prd": "yes"
"logs-entityanalytics_ad.entity-tst": "yes"
"logs-entityanalytics_ad.user-acc": "yes"
"logs-entityanalytics_ad.user-default": "yes"
"logs-entityanalytics_ad.user-ont": "yes"
"logs-entityanalytics_ad.user-prd": "yes"
"logs-entityanalytics_ad.user-tst": "yes"
"logs-etw.winlog-acc": "yes"
"logs-etw.winlog-default": "yes"
"logs-etw.winlog-ont": "yes"
"logs-etw.winlog-prd": "yes"
"logs-etw.winlog-tst": "yes"
"logs-extranet": "yes"
"logs-filestream.conjur-acc": "yes"
"logs-filestream.conjur-default": "yes"
"logs-filestream.conjur-ont": "yes"
"logs-filestream.conjur-prd": "yes"
"logs-filestream.conjur-tst": "yes"
"logs-filestream.generic-acc": "yes"
"logs-filestream.generic-default": "yes"
"logs-filestream.generic-ont": "yes"
"logs-filestream.generic-prd": "yes"
"logs-filestream.generic-purpleteaming": "yes"
"logs-filestream.generic-tst": "yes"
"logs-filestream.sap.securitycontrol-acc": "yes"
"logs-filestream.sap.securitycontrol-default": "yes"
"logs-filestream.sap.securitycontrol-ont": "yes"
"logs-filestream.sap.securitycontrol-prd": "yes"
"logs-filestream.sap.securitycontrol-tst": "yes"
"logs-filestream.squid-acc": "yes"
"logs-filestream.squid-default": "yes"
"logs-filestream.squid-ont": "yes"
"logs-filestream.squid-prd": "yes"
"logs-filestream.squid-tst": "yes"
"logs-fim.event-acc": "yes"
"logs-fim.event-default": "yes"
"logs-fim.event-ont": "yes"
"logs-fim.event-prd": "yes"
"logs-fim.event-tst": "yes"
"logs-fireeye.nx-acc": "yes"
"logs-fireeye.nx-default": "yes"
"logs-fireeye.nx-ont": "yes"
"logs-fireeye.nx-prd": "yes"
"logs-fireeye.nx-tst": "yes"
"logs-fortinet_fortigate.log-acc": "yes"
"logs-fortinet_fortigate.log-default": "yes"
"logs-fortinet_fortigate.log-ont": "yes"
"logs-fortinet_fortigate.log-prd": "yes"
"logs-fortinet_fortigate.log-tst": "yes"
"logs-fortinet_fortimanager.log-acc": "yes"
"logs-fortinet_fortimanager.log-default": "yes"
"logs-fortinet_fortimanager.log-ont": "yes"
"logs-fortinet_fortimanager.log-prd": "yes"
"logs-fortinet_fortimanager.log-tst": "yes"
"logs-generic-acc": "yes"
"logs-generic-default": "yes"
"logs-generic-ont": "yes"
"logs-generic-prd": "yes"
"logs-generic-tst": "yes"
"logs-infoblox_nios.log-acc": "yes"
"logs-infoblox_nios.log-default": "yes"
"logs-infoblox_nios.log-ont": "yes"
"logs-infoblox_nios.log-prd": "yes"
"logs-infoblox_nios.log-tst": "yes"
"logs-kibana.audit-default": "yes"
"logs-kubernetes.audit_logs-acc": "yes"
"logs-kubernetes.audit_logs-default": "yes"
"logs-kubernetes.audit_logs-ont": "yes"
"logs-kubernetes.audit_logs-prd": "yes"
"logs-kubernetes.audit_logs-tst": "yes"
"logs-linlog.cams3-acc": "yes"
"logs-linlog.cams3-default": "yes"
"logs-linlog.cams3-ont": "yes"
"logs-linlog.cams3-prd": "yes"
"logs-linlog.cams3-tst": "yes"
"logs-linlog.postfix-acc": "yes"
"logs-linlog.postfix-default": "yes"
"logs-linlog.postfix-ont": "yes"
"logs-linlog.postfix-prd": "yes"
"logs-linlog.postfix-tst": "yes"
"logs-logmanagement": "yes"
"logs-logstash.log-acc": "yes"
"logs-logstash.log-default": "yes"
"logs-logstash.log-ont": "yes"
"logs-logstash.log-prd": "yes"
"logs-logstash.log-tst": "yes"
"logs-mysql.error-default": "yes"
"logs-mysql.slowlog-default": "yes"
"logs-netwerk-services": "yes"
"logs-nexpose-acc": "yes"
"logs-nexpose-default": "yes"
"logs-nexpose-ont": "yes"
"logs-nexpose-prd": "yes"
"logs-nexpose-tst": "yes"
"logs-nginx-prod": "yes"
"logs-nginx.access-default": "yes"
"logs-nginx.error-default": "yes"
"logs-oracle.database_audit-default": "yes"
"logs-osquery_manager.action.responses-acc": "yes"
"logs-osquery_manager.action.responses-default": "yes"
"logs-osquery_manager.action.responses-ont": "yes"
"logs-osquery_manager.action.responses-prd": "yes"
"logs-osquery_manager.action.responses-tst": "yes"
"logs-osquery_manager.result-acc": "yes"
"logs-osquery_manager.result-default": "yes"
"logs-osquery_manager.result-ont": "yes"
"logs-osquery_manager.result-prd": "yes"
"logs-osquery_manager.result-tst": "yes"
"logs-postgresql.log-acc": "yes"
"logs-postgresql.log-default": "yes"
"logs-postgresql.log-ont": "yes"
"logs-postgresql.log-prd": "yes"
"logs-postgresql.log-tst": "yes"
"logs-proofpoint_tap.clicks_blocked-default": "yes"
"logs-proofpoint_tap.messages_delivered-default": "yes"
"logs-system.application-acc": "yes"
"logs-system.application-default": "yes"
"logs-system.application-ont": "yes"
"logs-system.application-prd": "yes"
"logs-system.application-tst": "yes"
"logs-system.auth-acc": "yes"
"logs-system.auth-default": "yes"
"logs-system.auth-ont": "yes"
"logs-system.auth-prd": "yes"
"logs-system.auth-tst": "yes"
"logs-system.security-acc": "yes"
"logs-system.security-default": "yes"
"logs-system.security-ont": "yes"
"logs-system.security-prd": "yes"
"logs-system.security-tst": "yes"
"logs-system.syslog-acc": "yes"
"logs-system.syslog-default": "yes"
"logs-system.syslog-ont": "yes"
"logs-system.syslog-prd": "yes"
"logs-system.syslog-tst": "yes"
"logs-system.system-acc": "yes"
"logs-system.system-default": "yes"
"logs-system.system-ont": "yes"
"logs-system.system-prd": "yes"
"logs-system.system-tst": "yes"
"logs-vmware": "yes"
"logs-windows.forwarded-acc": "yes"
"logs-windows.forwarded-default": "yes"
"logs-windows.forwarded-ont": "yes"
"logs-windows.forwarded-prd": "yes"
"logs-windows.forwarded-tst": "yes"
"logs-windows.powershell_operational-acc": "yes"
"logs-windows.powershell_operational-default": "yes"
"logs-windows.powershell_operational-ont": "yes"
"logs-windows.powershell_operational-prd": "yes"
"logs-windows.powershell_operational-tst": "yes"
"logs-windows.powershell-acc": "yes"
"logs-windows.powershell-default": "yes"
"logs-windows.powershell-ont": "yes"
"logs-windows.powershell-prd": "yes"
"logs-windows.powershell-tst": "yes"
"logs-windows.windows_defender-acc": "yes"
"logs-windows.windows_defender-default": "yes"
"logs-windows.windows_defender-ont": "yes"
"logs-windows.windows_defender-prd": "yes"
"logs-windows.windows_defender-tst": "yes"
"logs-winlog.defender-acc": "yes"
"logs-winlog.defender-default": "yes"
"logs-winlog.defender-ont": "yes"
"logs-winlog.defender-prd": "yes"
"logs-winlog.defender-tst": "yes"
"logs-winlog.terminalservices-acc": "yes"
"logs-winlog.terminalservices-default": "yes"
"logs-winlog.terminalservices-ont": "yes"
"logs-winlog.terminalservices-prd": "yes"
"logs-winlog.terminalservices-tst": "yes"
"logs-winlog.winlog-acc": "yes"
"logs-winlog.winlog-default": "yes"
"logs-winlog.winlog-ont": "yes"
"logs-winlog.winlog-prd": "yes"
"logs-winlog.winlog-tst": "yes"
"metrics-elastic_agent.elastic_agent-default": "yes"
"metrics-endpoint.metadata_current_default": "yes"
"metrics-kibana.stats-default": "yes"
"metrics-logstash.node_stats-default": "yes"
"metrics-mysql.status-default": "yes"
"metrics-nginx.stubstatus-default": "yes"
"metrics-oracle.performance-default": "yes"
"metrics-oracle.tablespace-default": "yes"
"test-dataset": "yes"
